apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS UsersService
      DEFAULT CHARACTER SET utf8mb4
      COLLATE utf8mb4_general_ci;

    CREATE DATABASE IF NOT EXISTS BoardsService
      DEFAULT CHARACTER SET utf8mb4
      COLLATE utf8mb4_general_ci;

    CREATE TABLE UsersService.users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      user_id VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL UNIQUE,
      password VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      email VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL UNIQUE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    CREATE TABLE BoardsService.boards (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      title VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      content TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
      author_id INT NOT NULL,
      CONSTRAINT fk_author FOREIGN KEY (author_id)
        REFERENCES UsersService.users(id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
