apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.rootPassword }}
  MSA_USER: {{ .Values.msaUser.name }}
  MSA_PASSWORD: {{ .Values.msaUser.password }}
