backend:
  boards:
    image: 235084396989.dkr.ecr.ap-northeast-2.amazonaws.com/backend-boards
    tag: 5
    port: 8080

mariadb:
  host: mariadb.default.svc.cluster.local
  port: 3306
  userName: MSA_User
  rootPassword: P@ssw0rd